export enum DemandCategory {
  PUBLIC_LIGHTING     = 'PUBLIC_LIGHTING',
  ROAD_MAINTENANCE    = 'ROAD_MAINTENANCE',
  GARBAGE_COLLECTION  = 'GARBAGE_COLLECTION',
  SANITATION          = 'SANITATION',
  INSPECTION          = 'INSPECTION',
  OTHER               = 'OTHER',
}